apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  labels:
    app: your-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
        - name: your-app-container
          image: ghcr.io/nickgulrajani/ghubcr_awsdeployment:DEV
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: my-secret

