name: Test Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          docker build -t ghcr.io/nickgulrajani/ghubcr_awsdeployment:DEV .
          docker login ghcr.io -u nickgulrajani -p $GH_TOKEN
          docker push ghcr.io/nickgulrajani/ghubcr_awsdeployment:DEV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS Fargate
        run: |
          # Replace with your Fargate deployment commands
          # Example:
          aws ecs update-service --cluster nick_python_app_cluster --service nick_python_app_service --force-new-deployment
