name: Test Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          docker build -t ghcr.io/nickgulrajani/ghubcr_awsdeployment:DEV .
          docker login ghcr.io -u nickgulrajani -p $GH_TOKEN
          docker push ghcr.io/nickgulrajani/ghubcr_awsdeployment:DEV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS EKS
        run: |
          aws eks update-kubeconfig --name new_python_app --region us-east-1
          kubectl apply -f python-app-deployment.yaml
        shell: /usr/bin/bash -e {0}
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Pull Docker image from GitHub Registry
        run: |
          docker pull ghcr.io/nickgulrajani/ghubcr_awsdeployment:DEV

      - name: Run local test
        run: |
          # Replace with your test commands
          # Example:
          docker run ghcr.io/nickgulrajani/ghubcr_awsdeployment:DEV python app.py

