name: Test Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          docker build -t ghcr.io/nickgulrajani/ghubcr_awsdeployment:DEV .
          docker login ghcr.io -u nickgulrajani -p $GH_TOKEN
          docker push ghcr.io/nickgulrajani/ghubcr_awsdeployment:DEV
